// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	myId: () => __TAURI_INVOKE<MyId>("my_id"),
	/**
	 *  The folder accepted files are saved to unless an Offer names another (shown on the Offer
	 *  sheet and in Settings).
	 */
	saveFolder: () => __TAURI_INVOKE<string>("save_folder"),
	/**
	 *  Makes `path` the save folder (made if missing, and it must be writable) from the next Offer
	 *  on; resolves to the folder as kept.
	 */
	setSaveFolder: (path: string) => __TAURI_INVOKE<string>("set_save_folder", { path }),
	/**  Whether first run is still to be done: the UI shows its screen instead of the tabs. */
	needsFirstRun: () => __TAURI_INVOKE<boolean>("needs_first_run"),
	/**  Records that the user has been through first run. */
	finishFirstRun: () => __TAURI_INVOKE<null>("finish_first_run"),
	/**
	 *  Offers the files and folders at `paths` to the Device with the pasted Device ID `to`, as
	 *  one Transfer; resolves to the Transfer ID.
	 */
	sendFiles: (to: string, paths: string[]) => __TAURI_INVOKE<string>("send_files", { to, paths }),
	/**
	 *  Offers the files and folders at `paths` to every Device in `to` (pasted or chosen Device
	 *  IDs) at once, as a Batch of one Transfer each; resolves to the Batch ID.
	 */
	sendBatch: (to: string[], paths: string[]) => __TAURI_INVOKE<string>("send_batch", { to, paths }),
	/**  Offers `text` to the Device with the pasted Device ID `to`; resolves to the Transfer ID. */
	sendText: (to: string, text: string) => __TAURI_INVOKE<string>("send_text", { to, text }),
	/**
	 *  Offers `text` to every Device in `to` at once, as a Batch of one Transfer each; resolves to
	 *  the Batch ID.
	 */
	sendTextBatch: (to: string[], text: string) => __TAURI_INVOKE<string>("send_text_batch", { to, text }),
	/**  Stops every Transfer of a Batch that is still running. */
	cancelBatch: (batchId: BatchId) => __TAURI_INVOKE<null>("cancel_batch", { batchId }),
	/**  Sends a Failed Transfer of a Batch again, with a new Offer; resolves to the new Transfer ID. */
	retryTransfer: (transferId: TransferId) => __TAURI_INVOKE<string>("retry_transfer", { transferId }),
	/**  Whether a pending Offer fits in `folder` (the save folder when absent). */
	checkOffer: (transferId: TransferId, folder: string | null) => __TAURI_INVOKE<SpaceCheck>("check_offer", { transferId, folder }),
	/**  Accepts a pending Offer into `folder` for this Offer only (the save folder when absent). */
	acceptOffer: (transferId: TransferId, folder: string | null) => __TAURI_INVOKE<null>("accept_offer", { transferId, folder }),
	declineOffer: (transferId: TransferId) => __TAURI_INVOKE<null>("decline_offer", { transferId }),
	/**  Stops a Transfer, on either side, until it starts saving. */
	cancelTransfer: (transferId: TransferId) => __TAURI_INVOKE<null>("cancel_transfer", { transferId }),
	/**  Sends an expired Offer again; resolves to the new Transfer ID. */
	resendTransfer: (transferId: TransferId) => __TAURI_INVOKE<string>("resend_transfer", { transferId }),
	/**  This Device's name, as other Devices see it. */
	deviceName: () => __TAURI_INVOKE<string>("device_name"),
	/**  Renames this Device; resolves to the name as stored (trimmed, shortened if too long). */
	setDeviceName: (name: string) => __TAURI_INVOKE<string>("set_device_name", { name }),
	/**  Who can see this Device as a Nearby Device. */
	visibility: () => __TAURI_INVOKE<Visibility>("visibility"),
	/**  Changes who can see this Device as a Nearby Device; it takes effect at once. */
	setVisibility: (visibility: Visibility) => __TAURI_INVOKE<null>("set_visibility", { visibility }),
	/**
	 *  Whether this Device uses the public Mainline DHT, besides n0 DNS, to publish its address and
	 *  find its Contacts'.
	 */
	publicDht: () => __TAURI_INVOKE<boolean>("public_dht"),
	/**  Turns the public DHT on or off; it takes effect at once and is kept across restarts. */
	setPublicDht: (on: boolean) => __TAURI_INVOKE<null>("set_public_dht", { on }),
	/**  Whether this Device starts when the user logs in. */
	autostartEnabled: () => __TAURI_INVOKE<boolean>("autostart_enabled"),
	setAutostart: (on: boolean) => __TAURI_INVOKE<null>("set_autostart", { on }),
	/**  Whether debug logging is on: a bigger log, for finding what went wrong. */
	debugLogging: () => __TAURI_INVOKE<boolean>("debug_logging"),
	/**  Turns debug logging on or off; it takes effect at once and is kept across restarts. */
	setDebugLogging: (on: boolean) => __TAURI_INVOKE<null>("set_debug_logging", { on }),
	/**  Writes the log files and an `about.txt` as a zip to `path`. Nothing is sent anywhere. */
	exportDiagnostics: (path: string) => __TAURI_INVOKE<null>("export_diagnostics", { path }),
	/**  The user confirmed quitting while Transfers are in progress: save their progress and exit. */
	quitApp: () => __TAURI_INVOKE<void>("quit_app"),
	/**
	 *  Looks for a newer release now (the "Update now" button). Rejects when the check fails, as it
	 *  does offline.
	 */
	checkForUpdate: () => __TAURI_INVOKE<UpdateAction>("check_for_update"),
	/**
	 *  The newer release the last check found, if any: what the UI asks for when it opens, as a
	 *  check at startup may have finished before it was listening.
	 */
	pendingUpdate: () => __TAURI_INVOKE<UpdateAction>("pending_update"),
	/**
	 *  Downloads `version`, the release the user agreed to install, replaces this AppImage with it
	 *  (the plugin checks the signature first), and starts the app again by the way out of quitting,
	 *  so that the Device saves its Transfers' progress: they resume in the new version. The UI
	 *  calls this only once the user has agreed (and, with Transfers in progress, been told they
	 *  stop for the restart). Refused if that is no longer the release found, if the app is
	 *  quitting, and for a deb or rpm install, which is never updated in place.
	 */
	installUpdate: (version: string) => __TAURI_INVOKE<null>("install_update", { version }),
	/**  Every Contact, in the order they were added. */
	contacts: () => __TAURI_INVOKE<Contact[]>("contacts"),
	/**
	 *  Saves the Device with the pasted Device ID as a Contact. `device_name` is the name to show
	 *  until the Contact is given a Nickname. The UI asks the user to check the Fingerprint first.
	 */
	addContact: (id: string, deviceName: string | null) => __TAURI_INVOKE<Contact>("add_contact", { id, deviceName }),
	/**  Sets a Contact's Nickname; absent or empty goes back to its Device Name. */
	setNickname: (id: string, nickname: string | null) => __TAURI_INVOKE<Contact>("set_nickname", { id, nickname }),
	setAutoAccept: (id: string, on: boolean) => __TAURI_INVOKE<Contact>("set_auto_accept", { id, on }),
	/**  Forgets a Contact; its Transfer records stay. */
	removeContact: (id: string) => __TAURI_INVOKE<null>("remove_contact", { id }),
	/**
	 *  Transfer History, newest first, narrowed by whichever are given: the other Device's ID
	 *  (`peer`), the role this Device played (`direction`) and a search of the item names.
	 */
	history: (peer: string | null, direction: "sender" | "receiver" | null, search: string | null) => __TAURI_INVOKE<HistoryEntry[]>("history", { peer, direction, search }),
	/**  Deletes one Transfer that has ended from History. */
	deleteHistoryTransfer: (transferId: TransferId) => __TAURI_INVOKE<null>("delete_history_transfer", { transferId }),
	/**  Deletes the Transfers of a Batch that have ended from History; resolves to how many. */
	deleteHistoryBatch: (batchId: BatchId) => __TAURI_INVOKE<number>("delete_history_batch", { batchId }),
	/**  Clears History of every Transfer that has ended; resolves to how many. */
	clearHistory: () => __TAURI_INVOKE<number>("clear_history"),
	/**  Writes this Device's identity, protected by `password`, to the file at `path`. */
	exportIdentity: (path: string, password: string) => __TAURI_INVOKE<null>("export_identity", { path, password }),
	/**  Whose identity the file at `path` holds, if `password` opens it. Changes nothing. */
	checkIdentityImport: (path: string, password: string) => __TAURI_INVOKE<IdentityOwner>("check_identity_import", { path, password }),
	/**  How many Transfers are in progress, which a new identity stops: the count quitting asks about. */
	transfersInProgress: () => __TAURI_INVOKE<number>("transfers_in_progress"),
	/**
	 *  Replaces this Device's identity with the one in the file at `path`, and starts the app again
	 *  to take it up, as it was started from the menu or the desktop: whatever it was launched with
	 *  (to stay in the tray, to open a link) is not repeated. Importing the Device's own identity
	 *  changes nothing and does not restart.
	 */
	importIdentity: (path: string, password: string) => __TAURI_INVOKE<null>("import_identity", { path, password }),
	/**
	 *  Not a Device command: the UI calls it once it is listening for `DeviceEvent`s, and
	 *  receives everything the Device emitted before that, in order.
	 */
	eventsReady: () => __TAURI_INVOKE<void>("events_ready"),
};

/** Events */
export const events = {
	deviceEvent: makeEvent<DeviceEvent>("device-event"),
	shellEvent: makeEvent<ShellEvent>("shell-event"),
};

/* Types */
/**
 *  A random 128-bit Batch ID, chosen by the Sender: what ties together the Transfers made by
 *  one send to several Receivers. It stays on the Sender; no Receiver is told it.
 */
export type BatchId = string;

/**  A saved Device. */
export type Contact = {
	id: DeviceId,
	/**  The name this Device gave the Contact; shown instead of the Device Name. */
	nickname: string | null,
	/**  The Contact's own name for itself, as last learned (a share link suggests one). */
	device_name: string | null,
	/**  Accept this Contact's Offers without asking. Off by default. */
	auto_accept: boolean,
	last_known_address: KnownAddress,
	added_at: number,
};

/**  Every event the Device emits, in order, as one UI event. */
export type DeviceEvent = Event;

/**
 *  The permanent, shareable identifier of a Device: the iroh `EndpointId`, shown as
 *  52-character base32.
 */
export type DeviceId = string;

export type Event = {
	/**  Position in the stream, counting from 0 with no gaps. */
	seq: number,
	/**  When the Device emitted it, by the injected clock. */
	at: number,
} & EventKind;

export type EventKind = 
/**  A Transfer was created or moved to a new state, on either side. */
{
	type: "transfer",
} & TransferEvent | 
/**  How much of a Transfer's content a Receiver has downloaded so far. */
{
	type: "progress",
} & ProgressEvent | 
/**  A Transfer's files started or finished being hashed. */
{
	type: "preparing",
} & PreparingEvent | 
/**  The list of Nearby Devices changed. */
{
	type: "nearby",
} & NearbyEvent | 
/**
 *  Another Device runs a version of BhayanakShare that cannot exchange Transfers with this
 *  one, and was refused before any Offer.
 */
{
	type: "version_mismatch",
} & VersionMismatchEvent;

/**  A row of History, newest first. */
export type HistoryEntry = 
/**  A Transfer sent on its own, a Receiver's, or one of a Batch seen as a Device's. */
{ kind: "transfer"; transfer: HistoryTransfer } | 
/**
 *  A Sender's Batch, as one entry: its Transfers, oldest first, one for each time a
 *  Receiver was sent to (a retry follows the Transfer it retries).
 */
{ kind: "batch"; batch_id: BatchId; transfers: HistoryTransfer[] };

/**  A Transfer in History. */
export type HistoryTransfer = {
	record: TransferRecord,
	/**
	 *  For files this Device received and saved: whether what was saved is still where it was
	 *  put. `None` for every other Transfer, which has no saved location.
	 */
	saved_present: boolean | null,
};

/**  What went wrong with an identity export or import, in the terms the UI words differently. */
export type IdentityError = {
	kind: IdentityErrorKind,
	/**  For the kinds the UI has no wording of its own for. */
	message: string,
};

export type IdentityErrorKind = 
/**  The password does not open the file (or the file is damaged). */
"wrong_password" | "not_an_identity_file" | 
/**  The OS secret store cannot be used. */
"store_unavailable" | 
/**
 *  The store may hold either key, because replacing the old one failed half-way and so did
 *  putting it back.
 */
"replace_uncertain" | "other";

/**
 *  Whose identity a file holds: a Device ID and its Fingerprint, as for [`MyId`], but not this
 *  Device's.
 */
export type IdentityOwner = {
	/**  52-character base32 Device ID. */
	id: string,
	/**  First 8 characters, `XXXX-XXXX`. */
	fingerprint: string,
};

/**
 *  Where a Contact was last reached: its relay and the direct addresses seen on the latest
 *  successful connection. Empty until the first one.
 */
export type KnownAddress = {
	relay_url: string | null,
	direct: string[],
};

export type MyId = {
	/**  52-character base32 Device ID. */
	id: string,
	/**  First 8 characters, `XXXX-XXXX`. */
	fingerprint: string,
};

/**  A Device found on the LAN. */
export type NearbyDevice = {
	id: DeviceId,
	/**
	 *  What the Device calls itself, as it announced. Untrusted text: show it next to the
	 *  Fingerprint. Absent if it announced none.
	 */
	name: string | null,
};

/**
 *  The Devices found on the LAN, after a change: one appeared, left, or announced a new name.
 *  Always the whole list, so a listener never has to track individual changes.
 */
export type NearbyEvent = {
	devices: NearbyDevice[],
};

/**  Which side of a version mismatch has to update. */
export type Outdated = 
/**  This Device runs the older version: the user can update it ("Update now"). */
"this_device" | 
/**  The other Device runs the older version: its owner has to update. */
"peer";

/**
 *  Whether a Transfer is Preparing: the Sender is hashing the files, which it does while the
 *  Receiver decides (spec section 4). It overlays the Offered and Accepted states, which are
 *  announced as before; once the Transfer is in any other state there is nothing to prepare.
 *  Sent for Transfers of files only, never for text.
 */
export type PreparingEvent = {
	transfer_id: TransferId,
	/**
	 *  True when hashing starts on the Sender or the Offer arrives on the Receiver; false once
	 *  the Sender is done, or the Receiver has been told so (`HashReady`).
	 */
	preparing: boolean,
};

/**
 *  Download progress of an accepted Transfer, reported by its Receiver while it is
 *  Transferring. The first report and the last (`bytes == total`) are always sent; the ones
 *  between are spaced out by the Device's clock.
 */
export type ProgressEvent = {
	transfer_id: TransferId,
	/**  Bytes of the file received so far. */
	bytes: number,
	/**  The file's size, as offered. */
	total: number,
};

/**  Which side of a Transfer a Device plays. */
export type Role = "sender" | "receiver";

/**  What the shell tells the UI that is not a Device event. */
export type ShellEvent = 
/**
 *  Files to send, from a second launch or the tray's "Send files…"; the user still has to
 *  say to whom.
 */
{ type: "send_files"; paths: string[] } | 
/**  A notification about this incoming Offer was clicked. */
{ type: "open_offer"; transfer_id: TransferId } | 
/**
 *  Quit was chosen while `active` Transfers are in progress; the UI asks, and answers with
 *  the `quit_app` command.
 */
{ type: "confirm_quit"; active: number } | 
/**  Shutdown has begun: the Device is saving its progress, which can take a while. */
{ type: "quitting" } | 
/**  A check found a release newer than this one; `action` is what to offer for it. */
{ type: "update_available"; action: UpdateAction };

/**  What an Offer needs, against what its save folder has. */
export type SpaceCheck = {
	/**  The Offer's total size in bytes. */
	needed: number,
	/**  Bytes free in the save folder; `None` when the platform cannot say. */
	free: number | null,
	/**
	 *  Some path in the Offer would be longer than the filesystem allows once it is under the
	 *  save folder, so the Offer cannot be accepted into this folder.
	 */
	paths_too_long: boolean,
};

export type TransferEvent = {
	transfer_id: TransferId,
	/**  This Device's role in the Transfer. */
	role: Role,
	/**  The other Device. */
	peer: DeviceId,
	/**
	 *  What the other Device calls itself, as it announced when connecting; absent until
	 *  known (a Sender learns it only once it has reached the Receiver). Untrusted text: show
	 *  it next to the Fingerprint.
	 */
	peer_name: string | null,
	/**  What the Transfer carries. */
	kind: TransferKind,
	/**  The first of `items`, for places with room for one name; empty for text. */
	name: string,
	/**  Bytes of files, or of text. */
	size: number,
	/**
	 *  The text of a `Text` Transfer, whole, on every event of it. Untrusted when received:
	 *  show it as plain text, never as markup.
	 */
	text: string | null,
	/**
	 *  The names at the top of what was offered: the files and folders the Sender picked, each
	 *  once. All of them are listed, however many; a screen shows as many as fit.
	 */
	items: string[],
	file_count: number,
	/**  Symlinks the Sender found in the folders it picked and left out. */
	skipped_links: number,
	/**
	 *  Names the Receiver changed to make them safe to write on every system (a Sender has
	 *  none to report).
	 */
	adjusted_names: number,
	/**
	 *  The Batch this Transfer is part of, on the Sender that made it (a Receiver has none).
	 *  Transfers with the same ID belong to one Batch row; each has its own state.
	 */
	batch_id: BatchId | null,
	/**
	 *  When the Offer lapses if nobody answers it, by this Device's clock. The same on every
	 *  event of the Transfer, so a late subscriber can show the countdown.
	 */
	expires_at: number,
	state: TransferState,
};

/**
 *  A random 128-bit Transfer ID, chosen by the Sender. Hex in text and JSON, raw bytes on
 *  the wire.
 */
export type TransferId = string;

/**  What a Transfer carries. */
export type TransferKind = 
/**  Files and folders, saved into the save folder. */
"files" | 
/**
 *  A piece of text that travelled inline in the Offer. Text too long for that is sent as a
 *  file, so it is a `Files` Transfer.
 */
"text";

/**  One row of the Transfer table: an entry of Transfer History. */
export type TransferRecord = {
	id: TransferId,
	role: Role,
	/**  The other Device's ID (base32). */
	peer: string,
	/**
	 *  What the other Device called itself when it last connected for this Transfer; `None` if
	 *  it never did (an Offer that could not be delivered). Untrusted text.
	 */
	peer_name: string | null,
	/**  The first of `items`: what the Transfer is called where there is room for one name. */
	name: string,
	/**  What the Transfer carries: files, or text that went inline in the Offer. */
	kind: TransferKind,
	/**  Bytes of files, or of text. */
	size: number,
	/**
	 *  The whole text of a `Text` Transfer. A Receiver keeps it only once it has accepted:
	 *  text it declined, or that expired, is not kept. Untrusted when received.
	 */
	text: string | null,
	/**  The names at the top of what was offered: the files and folders the user picked. */
	items: string[],
	file_count: number,
	/**  Symlinks the Sender left out. */
	skipped_links: number,
	/**  Names a Receiver changed to make them safe to write (spec section 6). */
	adjusted_names: number,
	/**
	 *  The Batch a Sender made this Transfer in; `None` for a Transfer sent on its own and for
	 *  every Receiver's (a Receiver is never told about the Batch).
	 */
	batch_id: BatchId | null,
	state: TransferState,
	/**  When the Offer was made. */
	created_at: number,
	/**  When the Receiver said yes (or Auto-accept did); `None` if it never was accepted. */
	accepted_at: number | null,
	/**  When the state last changed: for a Transfer that has ended, when it ended. */
	updated_at: number,
};

/**  Where a Transfer is in its lifecycle (spec section 4, the part the skeleton covers). */
export type TransferState = { kind: "offered" } | { kind: "accepted" } | { kind: "declined" } | 
/**
 *  Sender only: the Receiver has accepted, but the Batch already has its limit of Receivers
 *  downloading, so this one waits for a slot. The Receiver shows Accepted meanwhile: it is
 *  not told, and fetches once the Sender sends `HashReady`.
 */
{ kind: "waiting" } | 
/**  The Receiver is fetching the content. */
{ kind: "transferring" } | 
/**
 *  The Receiver lost the Sender part-way through and is redialling it (Receiver only;
 *  the Sender just keeps showing Transferring).
 */
{ kind: "reconnecting" } | 
/**  The Receiver has everything and is moving it into the save folder. */
{ kind: "saving" } | 
/**  `saved_to` is set on the Receiver only. */
{ kind: "completed"; saved_to: string | null } | { kind: "failed"; reason: string } | 
/**  Nobody answered the Offer within 10 minutes ([`OFFER_TTL_MS`]). */
{ kind: "expired" } | 
/**  One side stopped the Transfer before it completed; `by` is which. */
{ kind: "cancelled"; by: Role };

/**  What to do about the latest release. */
export type UpdateAction = 
/**  Nothing newer, or nothing that could be compared. */
{ type: "none" } | 
/**  Offer to install `version` and restart: an AppImage. */
{ type: "install"; version: string } | 
/**  Offer a link to the release page for `version`: a package. */
{ type: "open_page"; version: string };

/**
 *  Why an update was not installed, in the terms the UI words (`update.error.*` in `i18n.ts`).
 *  Deliberately no message: the plugin's are English, and can name the AppImage's path.
 */
export type UpdateError = 
/**  This install is a package, which is never updated in place. */
"not_app_image" | 
/**  No newer release has been found. */
"none_pending" | 
/**  The release found is no longer the version the user agreed to: a newer check replaced it. */
"version_changed" | 
/**  Another install is running. */
"already_installing" | 
/**  The app is already quitting. */
"quitting" | 
/**  The download failed, as it does offline. */
"download_failed" | 
/**  The download was not signed by the update key, so it was not installed. */
"signature_invalid" | 
/**  Replacing the AppImage failed. */
"install_failed";

/**
 *  A connection with another Device was refused for the versions of BhayanakShare. Sent on
 *  both sides, whoever dialled, and for a resume as well as for a new Offer. A Sender also
 *  sees its Transfer fail, with the same advice in the reason.
 */
export type VersionMismatchEvent = {
	peer: DeviceId,
	/**  What the other Device calls itself, as it announced in its `Hello`. Untrusted text. */
	peer_name: string | null,
	/**  The other Device's app version, as it announced. Untrusted text. */
	peer_app_version: string | null,
	outdated: Outdated,
};

/**
 *  Who can see a Device as a Nearby Device (spec section 3). Governs discovery only: anyone
 *  holding the Device ID can still send to it.
 */
export type Visibility = 
/**  A plain announcement with the Device Name: anyone on the LAN sees it. */
"everyone" | 
/**  Only Devices that hold this Device's ID: a blinded beacon only they can recognise. */
"id_holders" | 
/**
 *  Nobody: announces nothing and looks for nobody, and only answers a Device that asks for
 *  it by its ID.
 */
"hidden";

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

