// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	myId: () => __TAURI_INVOKE<MyId>("my_id"),
	saveFolder: () => __TAURI_INVOKE<string>("save_folder"),
	/**
	 *  Offers the file at `path` to the Device with the pasted Device ID `to`; resolves to the
	 *  Transfer ID.
	 */
	sendFile: (to: string, path: string) => __TAURI_INVOKE<string>("send_file", { to, path }),
	/**  Whether a pending Offer fits in `folder` (the save folder when absent). */
	checkOffer: (transferId: TransferId, folder: string | null) => __TAURI_INVOKE<SpaceCheck>("check_offer", { transferId, folder }),
	/**  Accepts a pending Offer into `folder` for this Offer only (the save folder when absent). */
	acceptOffer: (transferId: TransferId, folder: string | null) => __TAURI_INVOKE<null>("accept_offer", { transferId, folder }),
	declineOffer: (transferId: TransferId) => __TAURI_INVOKE<null>("decline_offer", { transferId }),
	/**  Stops a Transfer, on either side, until it starts saving. */
	cancelTransfer: (transferId: TransferId) => __TAURI_INVOKE<null>("cancel_transfer", { transferId }),
	/**  Sends an expired Offer again; resolves to the new Transfer ID. */
	resendTransfer: (transferId: TransferId) => __TAURI_INVOKE<string>("resend_transfer", { transferId }),
	/**
	 *  Not a Device command: the UI calls it once it is listening for `DeviceEvent`s, and
	 *  receives everything the Device emitted before that, in order.
	 */
	eventsReady: () => __TAURI_INVOKE<void>("events_ready"),
};

/** Events */
export const events = {
	deviceEvent: makeEvent<DeviceEvent>("device-event"),
};

/* Types */
/**  Every event the Device emits, in order, as one UI event. */
export type DeviceEvent = Event;

/**
 *  The permanent, shareable identifier of a Device: the iroh `EndpointId`, shown as
 *  52-character base32.
 */
export type DeviceId = string;

export type Event = {
	/**  Position in the stream, counting from 0 with no gaps. */
	seq: number,
	/**  When the Device emitted it, by the injected clock. */
	at: number,
} & EventKind;

export type EventKind = 
/**  A Transfer was created or moved to a new state, on either side. */
{
	type: "transfer",
} & TransferEvent | 
/**  How much of a Transfer's content a Receiver has downloaded so far. */
{
	type: "progress",
} & ProgressEvent;

export type MyId = {
	/**  52-character base32 Device ID. */
	id: string,
	/**  First 8 characters, `XXXX-XXXX`. */
	fingerprint: string,
};

/**
 *  Download progress of an accepted Transfer, reported by its Receiver while it is
 *  Transferring. The first report and the last (`bytes == total`) are always sent; the ones
 *  between are spaced out by the Device's clock.
 */
export type ProgressEvent = {
	transfer_id: TransferId,
	/**  Bytes of the file received so far. */
	bytes: number,
	/**  The file's size, as offered. */
	total: number,
};

/**  Which side of a Transfer a Device plays. */
export type Role = "sender" | "receiver";

/**  What an Offer needs, against what its save folder has. */
export type SpaceCheck = {
	/**  The Offer's total size in bytes. */
	needed: number,
	/**  Bytes free in the save folder; `None` when the platform cannot say. */
	free: number | null,
};

export type TransferEvent = {
	transfer_id: TransferId,
	/**  This Device's role in the Transfer. */
	role: Role,
	/**  The other Device. */
	peer: DeviceId,
	name: string,
	size: number,
	/**
	 *  When the Offer lapses if nobody answers it, by this Device's clock. The same on every
	 *  event of the Transfer, so a late subscriber can show the countdown.
	 */
	expires_at: number,
	state: TransferState,
};

/**
 *  A random 128-bit Transfer ID, chosen by the Sender. Hex in text and JSON, raw bytes on
 *  the wire.
 */
export type TransferId = string;

/**  Where a Transfer is in its lifecycle (spec section 4, the part the skeleton covers). */
export type TransferState = { kind: "offered" } | { kind: "accepted" } | { kind: "declined" } | 
/**  The Receiver is fetching the content. */
{ kind: "transferring" } | 
/**  The Receiver has everything and is moving it into the save folder. */
{ kind: "saving" } | 
/**  `saved_to` is set on the Receiver only. */
{ kind: "completed"; saved_to: string | null } | { kind: "failed"; reason: string } | 
/**  Nobody answered the Offer within 10 minutes ([`OFFER_TTL_MS`]). */
{ kind: "expired" } | 
/**  One side stopped the Transfer before it completed; `by` is which. */
{ kind: "cancelled"; by: Role };

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

